### ISSUE TITLE
Crashes when there is no permission to access the camera.

### ISSUE THREAD

**Issue by thedp** [yuvirajsinh/YCameraView#15]
I've managed to trace a crash coming from lines 255 and 265: `[session addInput:input];`.
The crash happens when the user doesn't agree to provide camera access, which results in `input` to be `nil` and my app gets rejected during review :)

**Comment by yuvirajsinh** [comment]
@thedp Thanks to raise this issue.
It might be late to reply on this issue but I just updated controller and taken care for the crash you mentioned.
